const GET_ALL_USERS = "GET_ALL_USERS";
const EDIT_USER = "EDIT_USER";
const USERS_LOADING = "USERS_LOADING";
const GETS_SINGLE_USER = "GETS_SINGLE_USER";
const UPDATE_USER = "UPDATE_USER"

export {
  GET_ALL_USERS, USERS_LOADING, EDIT_USER, GETS_SINGLE_USER, UPDATE_USER
}
